# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-12 08:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
            ],
        ),
        migrations.AlterField(
            model_name='resumeitem',
            name='description',
            field=models.TextField(blank=True, max_length=2047),
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_items',
            field=models.ManyToManyField(to='resume.ResumeItem'),
        ),
        migrations.AddField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
